In [1]:
run eda2.py

eda2.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  bg_df['bg_appopen'] = 1

In [3]:
g = group_all_tables.copy()

In [2]:
group_all_tables.shape

(23654, 44)

In [5]:
g.columns

Index([                     u'user_id',                      u'appopen',
                       u'max_open/day',                      u'use_age',
                              u'churn',                      u'1w_open',
                            u'1w_crit',                      u'1wacute',
                        u'1w_bg_entry',                   u'1w_carbent',
                           u'1w_wtent',                   u'tot_wt_ent',
                      u'max_wtent/day',                    u'days_f0wt',
                    u'max_carbent/day',                   u'days_f0crb',
                        u'tot_carbent',                       u'min_bg',
                             u'max_bg',                       u'avg_bg',
                       u'tot_critical',                    u'tot_acute',
                        u'tot_bg_open',                  u'max_bg_open',
                        u'bg_user_age',                  u'BG_Schedule',
                  u'dateOfFirstLaunch',           u'Meal_Reminders_Set',
            u'TrackingExerciseMinutes',           u'Total_BG_Reminders',
                         u'carbBudget',    u'diabetes.type_Gestational',
                 u'diabetes.type_LADA',          u'diabetes.type_Other',
         u'diabetes.type_Pre-diabetic',    u'diabetes.type_Prediabetes',
               u'diabetes.type_Type I',        u'diabetes.type_Type II',
                      u'gender_Female',                  u'gender_Male',
       u'CarbEntryPreference_estimate',  u'CarbEntryPreference_numeric',
             u'UserTreatmentType_Both',       u'UserTreatmentType_Meds'],
      dtype='object')

In [8]:
g['tot_acute'].sum()

30704.0

In [9]:
g['tot_critical'].sum()

6910.0

In [10]:
g[g['tot_critical']>1][:10]

,user_id,appopen,max_open/day,use_age,churn,1w_open,1w_crit,1wacute,1w_bg_entry,1w_carbent,...,diabetes.type_Pre-diabetic,diabetes.type_Prediabetes,diabetes.type_Type I,diabetes.type_Type II,gender_Female,gender_Male,CarbEntryPreference_estimate,CarbEntryPreference_numeric,UserTreatmentType_Both,UserTreatmentType_Meds
43,44,42.0,8.0,112.0,0.0,27.0,3.0,4.0,18.0,NaN,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
49,50,1873.0,117.0,122.0,0.0,189.0,3.0,4.0,13.0,90.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
53,54,13.0,8.0,17.0,1.0,12.0,2.0,2.0,8.0,NaN,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
61,62,85.0,9.0,98.0,1.0,10.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
70,71,8.0,4.0,11.0,1.0,7.0,1.0,1.0,3.0,NaN,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
93,94,38.0,8.0,10.0,1.0,32.0,3.0,6.0,14.0,5.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
116,117,8.0,5.0,43.0,1.0,6.0,2.0,2.0,2.0,NaN,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
148,149,184.0,6.0,70.0,0.0,23.0,2.0,6.0,12.0,27.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
149,150,44.0,18.0,5.0,0.0,44.0,4.0,5.0,14.0,5.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
181,182,376.0,14.0,96.0,0.0,60.0,5.0,13.0,17.0,NaN,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [11]:
g['tot_critical'].describe()

/Users/Salma/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

count    15388.000000
mean         0.449051
std          3.485210
min          0.000000
25%               NaN
50%               NaN
75%               NaN
max        194.000000
Name: tot_critical, dtype: float64

In [12]:
g['tot_acute'].describe()

count    15388.000000
mean         1.995321
std          7.386980
min          0.000000
25%               NaN
50%               NaN
75%               NaN
max        202.000000
Name: tot_acute, dtype: float64

In [19]:
a

In [20]:
med_risk_patients.head()

     user_id  tot_acute  tot_critical
7          8        2.0           0.0
37        38        3.0           0.0
117      118        2.0           0.0
130      131        5.0           0.0
133      134        4.0           0.0

In [21]:
med_risk_patients.shape

(1598, 3)

In [29]:
med_risk_patients['user_id'].values.tolist()

[8,
 38,
 118,
 131,
 134,
 177,
 178,
 186,
 234,
 271,
 279,
 302,
 306,
 349,
 372,
 416,
 424,
 431,
 454,
 494,
 554,
 557,
 563,
 579,
 618,
 669,
 707,
 708,
 731,
 781,
 828,
 857,
 888,
 892,
 978,
 987,
 1015,
 1038,
 1039,
 1048,
 1056,
 1110,
 1127,
 1131,
 1162,
 1209,
 1287,
 1298,
 1338,
 1341,
 1369,
 1379,
 1382,
 1393,
 1406,
 1437,
 1500,
 1570,
 1610,
 1620,
 1637,
 1645,
 1656,
 1662,
 1688,
 1699,
 1712,
 1722,
 1729,
 1740,
 1767,
 1776,
 1781,
 1817,
 1856,
 1884,
 1894,
 1899,
 1905,
 1952,
 1985,
 1997,
 2016,
 2028,
 2055,
 2081,
 2107,
 2147,
 2150,
 2164,
 2167,
 2244,
 2285,
 2291,
 2340,
 2422,
 2432,
 2445,
 2456,
 2465,
 2517,
 2529,
 2540,
 2542,
 2548,
 2642,
 2661,
 2664,
 2678,
 2722,
 2730,
 2757,
 2760,
 2819,
 2831,
 2849,
 2931,
 2940,
 2954,
 2970,
 2978,
 2983,
 2987,
 3000,
 3032,
 3036,
 3047,
 3074,
 3089,
 3108,
 3114,
 3156,
 3164,
 3192,
 3193,
 3242,
 3253,
 3338,
 3343,
 3373,
 3387,
 3395,
 3398,
 3402,
 3410,
 3421,
 3444,
 3449,
 3467,
 3485,
 3516,
 3536,
 3541,
 3545,
 3549,
 3552,
 3628,
 3647,
 3694,
 3705,
 3720,
 3734,
 3743,
 3781,
 3788,
 3819,
 3826,
 3837,
 3871,
 3899,
 3989,
 3994,
 3999,
 4011,
 4020,
 4023,
 4039,
 4045,
 4129,
 4130,
 4162,
 4212,
 4305,
 4422,
 4480,
 4481,
 4500,
 4532,
 4555,
 4565,
 4573,
 4581,
 4618,
 4624,
 4625,
 4646,
 4653,
 4657,
 4689,
 4761,
 4762,
 4778,
 4842,
 4932,
 4969,
 4993,
 5007,
 5030,
 5041,
 5063,
 5067,
 5077,
 5078,
 5091,
 5108,
 5143,
 5165,
 5166,
 5176,
 5177,
 5184,
 5214,
 5217,
 5224,
 5244,
 5315,
 5326,
 5346,
 5433,
 5446,
 5552,
 5557,
 5564,
 5577,
 5584,
 5604,
 5620,
 5662,
 5677,
 5697,
 5732,
 5742,
 5745,
 5766,
 5779,
 5835,
 5836,
 5877,
 5923,
 5987,
 6032,
 6042,
 6067,
 6072,
 6180,
 6203,
 6210,
 6226,
 6255,
 6302,
 6325,
 6328,
 6343,
 6346,
 6349,
 6351,
 6383,
 6390,
 6424,
 6441,
 6474,
 6477,
 6574,
 6609,
 6660,
 6696,
 6726,
 6739,
 6742,
 6764,
 6785,
 6812,
 6824,
 6906,
 6913,
 6943,
 6968,
 6995,
 7046,
 7106,
 7155,
 7226,
 7301,
 7362,
 7389,
 7393,
 7396,
 7411,
 7416,
 7421,
 7437,
 7583,
 7593,
 7603,
 7682,
 7685,
 7713,
 7751,
 7784,
 7805,
 7829,
 7863,
 7868,
 7888,
 7945,
 7954,
 7964,
 7965,
 7980,
 8001,
 8019,
 8022,
 8031,
 8046,
 8063,
 8065,
 8079,
 8117,
 8190,
 8196,
 8243,
 8257,
 8360,
 8378,
 8380,
 8386,
 8411,
 8439,
 8486,
 8496,
 8525,
 8534,
 8537,
 8549,
 8677,
 8697,
 8786,
 8797,
 8824,
 8847,
 8870,
 8877,
 8975,
 8999,
 9017,
 9025,
 9040,
 9062,
 9069,
 9082,
 9111,
 9115,
 9135,
 9158,
 9160,
 9209,
 9238,
 9251,
 9355,
 9356,
 9376,
 9397,
 9523,
 9531,
 9577,
 9610,
 9626,
 9635,
 9660,
 9661,
 9697,
 9718,
 9764,
 9770,
 9808,
 9817,
 9826,
 9856,
 9895,
 9958,
 10004,
 10010,
 10024,
 10026,
 10061,
 10098,
 10103,
 10171,
 10220,
 10250,
 10279,
 10280,
 10293,
 10306,
 10390,
 10412,
 10458,
 10466,
 10477,
 10487,
 10494,
 10505,
 10515,
 10550,
 10582,
 10616,
 10631,
 10717,
 10743,
 10848,
 10858,
 10876,
 10886,
 10931,
 10969,
 10970,
 11029,
 11042,
 11073,
 11100,
 11175,
 11197,
 11248,
 11267,
 11282,
 11293,
 11302,
 11354,
 11492,
 11493,
 11501,
 11518,
 11525,
 11581,
 11806,
 11898,
 11903,
 11923,
 11966,
 11983,
 12064,
 12113,
 12144,
 12174,
 12175,
 12180,
 12185,
 12214,
 12270,
 12298,
 12337,
 12381,
 12382,
 12424,
 12436,
 12456,
 12510,
 12549,
 12558,
 12588,
 12599,
 12600,
 12610,
 12620,
 12631,
 12642,
 12651,
 12666,
 12711,
 12717,
 12743,
 12770,
 12785,
 12809,
 12842,
 12857,
 12863,
 12894,
 12899,
 12919,
 12959,
 12965,
 12990,
 13046,
 13049,
 13059,
 13064,
 13093,
 13135,
 13155,
 13180,
 13242,
 13261,
 13282,
 13291,
 13293,
 13328,
 13333,
 13396,
 13431,
 13474,
 13496,
 13509,
 13524,
 13555,
 13576,
 13596,
 13647,
 13713,
 13732,
 13764,
 13902,
 13961,
 13964,
 14008,
 14015,
 14055,
 14087,
 14112,
 14120,
 14175,
 14204,
 14257,
 14279,
 14293,
 14302,
 14304,
 14308,
 14334,
 14338,
 14348,
 14379,
 14385,
 14388,
 14482,
 14491,
 14508,
 14512,
 14584,
 14632,
 14654,
 14691,
 14752,
 14758,
 14773,
 14782,
 14785,
 14796,
 14826,
 14838,
 14911,
 14934,
 15004,
 15006,
 15034,
 15041,
 15072,
 15088,
 15101,
 15112,
 15113,
 15116,
 15161,
 15196,
 15246,
 15272,
 15273,
 15335,
 15365,
 15366,
 15401,
 15414,
 15417,
 15443,
 15484,
 15485,
 15491,
 15510,
 15534,
 15537,
 15541,
 15556,
 15580,
 15589,
 15603,
 15654,
 15681,
 15682,
 15699,
 15846,
 15866,
 15884,
 15895,
 15911,
 15912,
 15923,
 15976,
 16012,
 16018,
 16049,
 16075,
 16076,
 16088,
 16131,
 16137,
 16155,
 16194,
 16237,
 16269,
 16279,
 16292,
 16315,
 16329,
 16339,
 16344,
 16356,
 16374,
 16376,
 16377,
 16465,
 16481,
 16491,
 16493,
 16508,
 16552,
 16606,
 16663,
 16724,
 16730,
 16765,
 16792,
 16872,
 16902,
 16915,
 17016,
 17023,
 17062,
 17070,
 17092,
 17104,
 17190,
 17226,
 17234,
 17258,
 17267,
 17271,
 17272,
 17325,
 17336,
 17339,
 17354,
 17400,
 17443,
 17570,
 17580,
 17647,
 17713,
 17729,
 17732,
 17779,
 17793,
 17810,
 17811,
 17848,
 17899,
 17909,
 17921,
 17930,
 17943,
 17992,
 18001,
 18003,
 18026,
 18147,
 18167,
 18176,
 18204,
 18228,
 18241,
 18274,
 18284,
 18287,
 18322,
 18369,
 18377,
 18383,
 18409,
 18456,
 18458,
 18478,
 18538,
 18624,
 18644,
 18658,
 18747,
 18756,
 18829,
 18847,
 18860,
 18863,
 18869,
 18925,
 18948,
 18949,
 19026,
 19037,
 19068,
 19079,
 19165,
 19174,
 19291,
 19301,
 19316,
 19337,
 19404,
 19415,
 19421,
 19452,
 19530,
 19571,
 19582,
 19592,
 19608,
 19624,
 19639,
 19647,
 19650,
 19687,
 19746,
 19749,
 19755,
 19781,
 19788,
 19796,
 19821,
 19826,
 19847,
 19854,
 19888,
 19905,
 19994,
 20067,
 20147,
 20172,
 20190,
 20202,
 20206,
 20275,
 20280,
 20288,
 20295,
 20318,
 20320,
 20321,
 20322,
 20389,
 20397,
 20427,
 20439,
 20451,
 20452,
 20471,
 20534,
 20571,
 20660,
 20665,
 20669,
 20679,
 20683,
 20747,
 20763,
 20795,
 20839,
 20867,
 20924,
 21001,
 21015,
 21051,
 21085,
 21124,
 21151,
 21165,
 21235,
 21251,
 21262,
 21266,
 21315,
 21352,
 21357,
 21384,
 21388,
 21408,
 21410,
 21419,
 21493,
 21500,
 21538,
 21540,
 21544,
 21563,
 21576,
 21635,
 21668,
 21746,
 21770,
 21886,
 21889,
 21891,
 21944,
 21945,
 21977,
 22012,
 22027,
 22047,
 22075,
 22081,
 22121,
 22139,
 22149,
 22153,
 22158,
 22198,
 22205,
 22243,
 22285,
 22362,
 22427,
 22440,
 22457,
 22470,
 22473,
 22476,
 22510,
 22520,
 22539,
 22541,
 22578,
 22591,
 22609,
 22617,
 22629,
 22638,
 22648,
 22729,
 22732,
 22770,
 22784,
 22788,
 22797,
 22815,
 22818,
 22835,
 22849,
 22862,
 22874,
 22912,
 22930,
 22948,
 22949,
 23010,
 23015,
 23020,
 23040,
 23053,
 23072,
 23117,
 23118,
 23127,
 23145,
 23165,
 23166,
 23186,
 23260,
 23302,
 23332,
 23350,
 23402,
 23407,
 23415,
 23434,
 23453,
 23515,
 23521,
 23584,
 23588,
 23589,
 23592,
 23619,
 23666,
 23703,
 23734,
 23743,
 23785,
 23801,
 23813,
 23818,
 23901,
 23904,
 23946,
 24009,
 24019,
 24025,
 24056,
 24078,
 24130,
 24139,
 24146,
 24150,
 24152,
 24153,
 24203,
 24204,
 24274,
 24281,
 24283,
 24363,
 24378,
 24401,
 24485,
 24516,
 24548,
 24595,
 24600,
 24612,
 24713,
 24765,
 24767,
 24768,
 24843,
 24849,
 24867,
 24888,
 24899,
 24929,
 24942,
 24961,
 24963,
 24965,
 24968,
 25026,
 25036,
 25042,
 25113,
 25137,
 25155,
 25174,
 25186,
 25202,
 25205,
 25209,
 25234,
 25263,
 25277,
 25294,
 25320,
 25322,
 25332,
 25334,
 25355,
 25367,
 25384,
 25504,
 25523,
 25543,
 25545,
 25571,
 25587,
 25659,
 25677,
 25694,
 25730,
 25762,
 25815,
 25829,
 25833,
 25861,
 25870,
 25903,
 25907,
 25948,
 26000,
 26052,
 26101,
 26178,
 26189,
 26206,
 26210,
 26221,
 26277,
 26320,
 ...]

In [22]:
high_risk_patients = g[(g['tot_acute']> 1) & (g['tot_critical']>1)][['user_id','tot_acute','tot_critical']]

In [23]:
high_risk_patients.head()

    user_id  tot_acute  tot_critical
43       44        4.0           3.0
49       50       23.0          17.0
53       54        2.0           2.0
61       62        2.0           2.0
70       71        2.0           2.0

In [24]:
high_risk_patients.shape

(913, 3)

In [26]:
bg_values.head()

,Date,bg,user_id,critical,acute,bg_appopen,max_open/day,days_f0bg,bins
0,2016-06-16 14:00:00,111.0,16170,0,0,1,4,46,"(42, 56]"
1,2016-06-15 05:00:00,127.0,16170,0,0,1,4,45,"(42, 56]"
2,2016-07-12 05:00:00,114.0,16170,0,0,1,4,72,"(70, 84]"
3,2016-06-03 06:00:00,111.0,16170,0,0,1,4,33,"(28, 42]"
4,2016-06-23 05:00:00,120.0,16170,0,0,1,4,53,"(42, 56]"

In [30]:
run eda2.py

ERROR:root:File `u'eda2.py'` not found.